# Generated by Django 5.1.7 on 2025-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('processed_query', models.TextField(blank=True)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'consulta chatbot',
                'verbose_name_plural': 'consultas chatbot',
            },
        ),
    ]
