# Generated by Django 5.1.7 on 2025-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquery',
            name='relevant_docs',
            field=models.TextField(blank=True),
        ),
    ]
