# Generated by Django 5.1.7 on 2025-04-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotquery_relevant_docs'),
    ]

    operations = [
    ]
