# Generated by Django 5.1.7 on 2025-04-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20250407_0801'),
    ]

    operations = [
    ]
