# obs la pág completa

import spacy
from spacy.lang.es.stop_words import STOP_WORDS

def corregir_texto(texto):
    for error, correccion in correcciones.items():
        texto = texto.lower().replace(error, correccion)
    return texto

correcciones ={
    "ke":"que",
    "k":"que",
    "xq":"por que",
    "pa":"para",
    "tbn":"también",
    "toy":"estoy",
    "toi":"estoy",
    "dnd":"donde",
    "kiero":"quiero",
    "sta":"esta",
    "stoy":"estoy",
    "ntnc":"entonces",
    "q tal":"qué tal",
     "teclado mecaniko": "teclado mecánico",
    "teclado mecanico": "teclado mecánico",
    "raton": "ratón",
    "mouse gamer": "ratón gamer",
    "monitor curvo": "monitor curvo",
    "pantaya": "pantalla",
    "pantaya gamer": "pantalla gamer",
    "grafica": "tarjeta gráfica",
    "grafika": "tarjeta gráfica",
    "placa madre": "placa base",
    "board": "placa base",
    "motherboard": "placa base",
    "memoria ram": "RAM",
    "almacenamiento ssd": "disco SSD",
    "almacenamiento hdd": "disco HDD",
    "gabinete gamer": "torre gamer",
    "case": "torre",
    "fuente poder": "fuente de poder",
    "fuente": "fuente de poder",
    "ventilador rgb": "ventilador RGB",
    "cooler": "disipador",
    "silla gammer": "silla gamer",
    "silla gamer": "silla gamer",
    "escritorio gamer": "mesa gamer",
    "control play": "control de PlayStation",
    "control xbox": "control de Xbox",
    "xbox x": "Xbox Series X",
    "xbox s": "Xbox Series S",
    "ps5": "PlayStation 5",
    "ps4": "PlayStation 4",
    "nintendo switch": "Nintendo Switch",
    "switch oled": "Nintendo Switch OLED",
    "switch lite": "Nintendo Switch Lite",
    "minecra": "Minecraft",
    "mincraf": "Minecraft",
    "micraf": "Minecraft",
    "fortnait": "Fortnite",
    "fornite": "Fortnite",
    "jueguitos": "videojuegos",
    "jueguito": "videojuego",
    "play": "PlayStation",
    "usb": "memoria USB",
    "micro sd": "tarjeta MicroSD",
    "auris": "auriculares",
    "cargador cel": "cargador de celular",
    "cargador lap": "cargador de laptop",
    "lap": "laptop",
    "pc gamer": "PC Gamer",
    "notebook": "laptop",
    "cpu": "procesador",
    "gpu": "tarjeta gráfica",
    "ssd": "disco SSD",
    "hdd": "disco HDD",
    "cámara": "cámara web",
    "camara": "cámara",
    "porq": "porque",
    "xk": "porque",
    "pq": "porque",
    "asi que": "así que",
    "nose": "no sé",
    "aunqueh": "aunque",
    "en tonces": "entonces",
    "tonces": "entonces",
    "entonses": "entonces",
    "dsp": "después",
    "luegp": "luego",
    "depues": "después",
    "ademas": "además",
    "aparte de eso": "además",
    "por lo tanto": "por lo tanto",
    "asi ": "asimismo",
    "por otro lado": "por otro lado",
    "en cambio": "en cambio",
    "tal vez": "tal vez",
    "de hecho": "de hecho",
    "aci que": "así que",
    "noc": "no sé",
    "noce": "no sé",
    "aun que": "aunque",
    "anque": "aunque",
    "desp": "después",
    "despue": "después",
    "de mas": "además",
    "admas": "además",
    "sinembargo": "sin embargo",
    "sin enbargo": "sin embargo",
    "sin en vargo": "sin embargo",
    "porlo tanto": "por lo tanto",
    "por lo tnto": "por lo tanto",
    "por lotanto": "por lo tanto",
    "asi mismo": "asimismo",
    "así mismo": "asimismo",
    "asi mismoo": "asimismo",
    "por consiguiente": "por consiguiente",
    "por consiquiente": "por consiguiente",
    "por consigiente": "por consiguiente",
    "en conclusion": "en conclusión",
    "conclucion": "conclusión",
    "en conclución": "en conclusión",
    "en resumen": "en resumen",
    "resumiendo": "en resumen",
    "por ejemplo": "por ejemplo",
    "xej": "por ejemplo",
    "ejem": "por ejemplo",
    "en fin": "en fin",
    "enfin": "en fin",
    "al final": "al final",
    "alfinal": "al final",
    "es decir": "es decir",
    "osea": "o sea",
    "ose": "o sea",
    "o sea": "o sea",
    "talvez": "tal vez",
    "tal ves": "tal vez",
    "talves": "tal vez",
    "quizas": "quizás",
    "quiza": "quizá",
    "kizas": "quizás",
    "kisa": "quizá",
    "deecho": "de hecho",
    "de echo": "de hecho",
    "valla": "vaya",
    "vaya": "vaya",
    "vaya a": "vaya a",
    "tenga": "tenga",
    "que tenga": "que tenga",
    "un": "un",
    "una": "una",
    "unos": "unos",
    "unas": "unas",
    "con": "con",
    "i": "y",
    "u":"u",
    "por ke": "porque",
    "ya qe": "ya que",
    "ya ke": "ya que",
    "yaque": "ya que",
    "pues": "pues",
    "puez": "pues",
    "puesto qe": "puesto que",
    "puesto ke": "puesto que",
    "puesto que": "puesto que",
    "dado qe": "dado que",
    "dado ke": "dado que",
    "dado que": "dado que",
    "debido a que": "debido a que",
    "debuidoi a q": "debido a que",
    "x eso": "por eso",
    "por eso": "por eso",
    "por eso mismo": "por eso mismo",
    "x":"por",
    "mejor dicho": "mejor dicho",
    "en otras palabras": "en otras palabras",
    "vale decir": "vale decir",
    "esto es": "esto es",
    "estoes": "esto es",
    "mejor dixo": "mejor dicho",
    "es dcir": "es decir",
    "en primer lugar": "en primer lugar",
    "primeramente": "primeramente",
    "segundo": "segundo",
    "en segundo lugar": "en segundo lugar",
    "por último": "por último",
    "finalmente": "finalmente",
    "para terminar": "para terminar",
    "para concluir": "para concluir",
    "en conclucion": "en conclusión",
    "enconclusion": "en conclusión",
    "hbaer":"a ver",
    "haber":"a ver",
    "alla":"haya",
    "aserca": "acerca",
    "aser": "hacer",
    "aserlo": "hacerlo",
    "aver": "a ver",
    "abeses": "a veces",
    "avesez": "a veces",
    "ahy": "hay",
    "ahi": "ahí",
    "hay": "hay",
    "ay": "hay",
    "ahy que": "hay que",
    "ay que": "hay que",
    "oi": "hoy",
    "oi dia": "hoy día",
    "oir": "oír",
    "toa": "toda",
    "to": "todo",
    "na": "nada",
    "q onda": "qué onda",
    "holi": "hola",
    "aki": "aquí",
    "aki toy": "aquí estoy",
    "toy bn": "estoy bien",
    "bn": "bien",
    "bno": "bueno",
    "klk": "¿qué tal?",
    "procesador amd": "procesador AMD",
    "intel i5": "Intel i5",
    "intel i7": "Intel i7",
    "grafica nvidia": "tarjeta gráfica NVIDIA",
    "grafica amd": "tarjeta gráfica AMD",
    "disco duro externo": "HDD externo",
    "memoria externa": "almacenamiento externo",
    "microfon": "micrófono",
    "micro": "micrófono",
    "cascos": "audífonos",
    "auris gamer": "auriculares gamer",
    "headset": "auriculares con micrófono",
    "lsta":"lista",
    "articulso":"articulos",

}

conectores_correctos = [
    "porque", "aunque", "así que", "entonces", "después", "además", "sin embargo",
    "por lo tanto", "asimismo", "por consiguiente", "en conclusión", "en resumen",
    "por ejemplo", "en fin", "al final", "es decir", "o sea", "tal vez", "quizás",
    "de hecho", "ya que", "de modo que", "en cambio", "por otro lado", "al contrario",
    "por el contrario", "si bien", "a pesar de", "con tal que", "mientras que",
    "puesto que", "dado que", "a causa de", "debido a", "según", "conforme",
    "por ende", "aunque", "más bien", "de todos modos", "así mismo","porque",
    "ya que","puesto que","dado que","debido a que","por eso","por eso mismo",
    "pues","o sea","es decir","en otras palabras","vale decir","esto es","mejor dicho",
    "en primer lugar","primeramente","en segundo lugar","segundo","por último","finalmente",
    "en resumen","para terminar","para concluir","en conclusión","al final","en fin","resumiendo"
]


def corregir_texto(texto):
    for error, correccion in correcciones.items():
        texto = texto.lower().replace(error, correccion)
    return texto

intenciones = {
    "consultar_producto": ["buscar", "encontrar", "quiero", "producto"],
    "comparar": ["diferencias", "comparar", "vs"],
    "precio": ["costar", "precio", "valor", "barato"]
}

def detectar_intencion(tokens):
    return [intencion for intencion, palabras in intenciones.items()
            if any(palabra in tokens for palabra in palabras)]


def extraer_entidades(tokens):
    entidades = {
        "productos": [],
        "atributos": ["color", "tamaño", "marca"]
    }

    # Aquí integrarías tu lógica de diccionarios especializados
    return entidades

sinonimos_productos = {
    "celular": ["móvil", "teléfono", "smartphone"],
    "tv": ["televisor", "pantalla", "television"]
}

def filtrar_stopwords(texto):
    palabras = texto.lower().split()
    return ' '.join([p for p in palabras if p not in STOP_WORDS])

def corregir_con_regex(texto, correcciones):
    patron = re.compile(r'\b(' + '|'.join(re.escape(k) for k in correcciones.keys()) + r')\b')
    return patron.sub(lambda x: correcciones[x.group()], texto.lower())
